### PR TITLE
Backwards compatibility on older magento version

### PR DESCRIPTION
**Pull request by vernard**
I tried your extension using Magento CE 1.4.2 (our company supports this version) and got a few errors. I'm hoping that we both want our extension to as much magento stores as possible and merge these changes.

### CODE REVIEW

**Comment by fbrnc** [comment]
I don't think it is a good idea to change the code to use these deprecated classes and use direct sql statements.
If you really need this to work with Magento versions that old I suggest you create a small "Upwards Compability Layer" that introduces the missing pieces:

Example 
```
if (!class_exists('Mage_Core_Model_Resource_Db_Abstract')) {
    class Mage_Core_Model_Resource_Db_Abstract extends Mage_Core_Model_Mysql4_Abstract {}
}
```

**Comment by vernard** [comment]
What about the direct sql statements?

**Comment by vernard** [comment]
Hmm.. That might be a solution... But where will we put this "Upwards Compatibility Layer"? 

Actually, I don't think they are deprecated classes... It's just that they wanted to remove the "Mysql4" as they intend to support other database engines.. The same with the `mysql4-install-{version}.php` scripts, now `install-{version}.php` scripts. It is because the `mysql4-install-{version}.php` scripts are solely for MySQL use.

What do you think?

**Comment by fbrnc** [comment]
Even if they're not going to remove it this is "outdated" and I don't think it's smalrt to continue to use this only to make some very old versions of Magento work with it (btw, I wouldn't be surprised if you faced other problems besides the ones you mentioned).

Since that "Upwards Compatibility Layer" is not Aoe_Profiler specific you should create a separate module for that.

**Comment by vernard** [comment]
We might have different perspective in these topics then.

However, it's your call. I'm just gonna leave it here. Thank you for your time.

**Pull request closed without merging**
